apiVersion: apps/v1
kind: Deployment
metadata:
  name: bench-v16
  namespace: frappe-v16
  labels:
    app: bench-v16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bench-v16
  template:
    metadata:
      labels:
        app: bench-v16
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: bench
          image: frappe/bench:latest
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: bench-data
              mountPath: /home/frappe/bench-data
      volumes:
        - name: bench-data
          persistentVolumeClaim:
            claimName: bench-v16-data
